import Head from "next/head";
import { useTheme } from 'next-themes'
import React, { useState, useEffect } from "react";

export default function Home() {
  const { theme, setTheme } = useTheme();
  const [dark, darkTheme] = useState('show');
  const [ light, lightTheme] = useState('hidden');

function inverted() {
  theme === 'light' ? darkTheme('show') : darkTheme('hidden')
  theme === 'light' ? lightTheme('hidden') : lightTheme('show')
  
}
useEffect(() => {
  inverted()
});
  return (
    <div>
        
      <Head>
        <title>Next App Dark Mode With Tailwind CSS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      

 
    <div  className="flex flex-col justify-center align-center items-center text-center h-screen">
      <button onClick={function(event){ setTheme(theme === 'light' ? 'dark' : 'light'); inverted();}}   id="" data-tooltip-target="tooltip-toggle" type="button" className=" hover:bg-gray-200 dark:hover:bg-gray-800 focus:outline-none rounded-md text-sm p-2.5">
        <svg aria-hidden="true" id="theme-toggle-dark-icon" className={`w-16 h-16 ${dark}`}fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path d="M17.293 13.293A8 8 0 016.707 2.707a8.001 8.001 0 1010.586 10.586z"></path></svg>
        <svg aria-hidden="true" id="theme-toggle-light-icon" className={`w-16 h-16 ${light}`} fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path d="M10 2a1 1 0 011 1v1a1 1 0 11-2 0V3a1 1 0 011-1zm4 8a4 4 0 11-8 0 4 4 0 018 0zm-.464 4.95l.707.707a1 1 0 001.414-1.414l-.707-.707a1 1 0 00-1.414 1.414zm2.12-10.607a1 1 0 010 1.414l-.706.707a1 1 0 11-1.414-1.414l.707-.707a1 1 0 011.414 0zM17 11a1 1 0 100-2h-1a1 1 0 100 2h1zm-7 4a1 1 0 011 1v1a1 1 0 11-2 0v-1a1 1 0 011-1zM5.05 6.464A1 1 0 106.465 5.05l-.708-.707a1 1 0 00-1.414 1.414l.707.707zm1.414 8.486l-.707.707a1 1 0 01-1.414-1.414l.707-.707a1 1 0 011.414 1.414zM4 11a1 1 0 100-2H3a1 1 0 000 2h1z" ></path></svg>
      </button>
    </div>
 




            
          
        
 
    </div>
  );
}